=== andyradz/aplios.solutions/sdk/sdk-core/src/main/resources/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="root" type="rootType">
    </xs:element>

    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element name="records" type="recordsType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="recordsType">
        <xs:sequence>
            <xs:element name="record" type="recordType" maxOccurs="unbounded"
                        minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="recordType">
        <xs:sequence>
            <xs:element type="xs:string" name="title" minOccurs="0"
                        maxOccurs="1" />
            <xs:element type="xs:string" name="artist" minOccurs="0"
                        maxOccurs="1" />
            <xs:element type="xs:string" name="genre" minOccurs="0"
                        maxOccurs="1" />
            <xs:element type="xs:short" name="year" minOccurs="1"
                        maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== andyradz/aplios.solutions/sdk/sdk-core/src/main/resources/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="customer.xsd">
    <records>
        <record>
            <title>Brand New Eyes</title>
            <artist>Paramore</artist>
            <genre>Punk Rock</genre>
            <year>2011</year>
        </record>
        <record>
            <title>My Yahho</title>
            <artist>Various Artist</artist>
            <genre>Rock</genre>
            <year>2013</year>
        </record>
        <record>
            <title>Scorpions</title>
            <artist>Rock Group</artist>
            <genre>Havy Metal</genre>
            <year>1991</year>
        </record>
        <record>
            <title>Limpbizkit</title>
            <artist>Pop Group</artist>
            <genre>Testeroble</genre>
            <year>2001</year>
        </record>
    </records>
</root>
